manifest:
  remotes:
    - name: zephyr-base
      url-base: https://github.com/zephyrproject-rtos
    - name: my-company-remote
      url-base: git@github.com:uLipe

  projects:
    - name: zephyr
      remote: zephyr-base
      revision: main
    - name: LinumDevBoardModule
      remote: my-company-remote
      revision: main
      path: my-company-modules/LinumDevBoardModule